<a href="https://colab.research.google.com/github/Yashu3624/6companies30Days/blob/main/WISE_ML_DAY_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hi I m YASWINI :)")

Hi I m YASWINI :)


In [3]:
a = [1,3,4,66,6]
print(type(a))

<class 'list'>


In [5]:
import numpy as np

In [18]:
arr_array = np.array([1,8,4,6])
print(type(arr_array))
print(arr_array)

<class 'numpy.ndarray'>
[1 8 4 6]


In [16]:
arr_arrange = np.arange(1,10)
print(type(arr_arrange))
print(arr_arrange)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


In [24]:
arr_linespace = np.linspace(1,10,6)
print(type(arr_linespace))
print(arr_linespace)

<class 'numpy.ndarray'>
[ 1.   2.8  4.6  6.4  8.2 10. ]


In [12]:
arr_ones = np.ones((3,3))
print(type(arr_ones))
print(arr_ones)

<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
arr_zeros = np.zeros((3,4))
print(type(arr_zeros))
print(arr_zeros)

<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
